let dinner = [
  {
    title: "Creamy Spaghetti",
    author: "Mohammad Sadeghiani",
    rate: 4,
    note: "This simple cacio e pepe recipe is super minimalist and easy to make. All you need is really just good cheese and pepper.",
    ingredients: [
      "6oz. pasta spaghetti",
      "1tsp unsalted butter",
      "1tsp fresh cracked black pepper",
      "1tsp salt",
      "1/3 cup grated Pecorino cheese",
      "1 cup grated Grana Padano cheese",
    ],
    category: 'dinner',
    country: 'italian',
    time: "20 minutes",
    step: [
      "Boil water in a pot. Season it with salt and then add pasta to cook.Stir occassionally until the pasta get tender.Before draining pasta reserve 3/4 cup of pasta cooking water.",
      "On a medium large skillet melt butter. Once the butter is melted, keep the temperature on medium heat and add pepper, cook until the pepper is toasted",
      "Add the reserved pasta water to the skillet and let simmer. Add pasta and all grated cheese. Stir and toss until cheese melts and creates creamy texture. Then the pasta is ready to serve.",
    ],
    image: "/image/creamypasta.jpg",
    date: "March 18 , 2024",
  },
  {
    title: "Potato",
    author: "Mohammad Sadeghiani",
    rate: 5,
    note: "Here is we are . Today im gonna show you how can i make potato khelal with soas.",
    ingredients: ["1kg potato", "50cc oil", "200g soas"],
    time: "15 minutes",
    step: [
      "Boil water in a pot. Season it with salt and then add pasta to cook.Stir occassionally until the pasta get tender.Before draining pasta reserve 3/4 cup of pasta cooking water.",
      "On a medium large skillet melt butter. Once the butter is melted, keep the temperature on medium heat and add pepper, cook until the pepper is toasted",
      "Add the reserved pasta water to the skillet and let simmer. Add pasta and all grated cheese. Stir and toss until cheese melts and creates creamy texture. Then the pasta is ready to serve.",
    ],
    category: 'breakfast',
    country: 'iran',
    image: "/image/potato.jpg",
  },
  {
    title: "Penne Arrabbiata",
    author: "Elena Rossi",
    rate: 4,
    note: "This spicy tomato sauce is quick and easy to make, perfect for a weeknight dinner.",
    ingredients: [
      "1 lb penne pasta",
      "1/4 cup olive oil",
      "4 cloves garlic, minced",
      "1 crushed red pepper flakes (adjust for spice preference)",
      "1 (28 oz) can crushed tomatoes",
      "1/2 cup chopped fresh basil",
      "1/4 cup grated Parmesan cheese",
      "Salt and pepper to taste",
    ],
    category: 'dinner',
    country: 'italian',
    time: "20 minutes",
    step: [
      "Cook pasta according to package directions. Reserve 1 cup of pasta water before draining.",
      "Heat olive oil in a large skillet over medium heat. Add garlic and red pepper flakes, and cook for 30 seconds, or until fragrant.",
      "Add crushed tomatoes and simmer for 10 minutes, stirring occasionally. Season with salt and pepper.",
      "Toss cooked pasta with the tomato sauce, reserving some pasta water for adjusting consistency if needed.",
      "Stir in basil and Parmesan cheese. Serve immediately.",
    ],
    date: "March 18, 2024",
    image: '/image/penne.jpg'
  },
  {
    title: "Chicken",
    category: 'dinner',
    country: 'italian',
    author: "Mohammad Sadeghiani",
    rate: 5,
    note: "Here is we are . Today im gonna show you how can i make potato khelal with soas.",
    ingredients: ["1kg potato", "50cc oil", "200g soas"],
    time: "20 minutes",
    date: "March 18 , 2024",
    step: [
      "Boil water in a pot. Season it with salt and then add pasta to cook.Stir occassionally until the pasta get tender.Before draining pasta reserve 3/4 cup of pasta cooking water.",
      "On a medium large skillet melt butter. Once the butter is melted, keep the temperature on medium heat and add pepper, cook until the pepper is toasted",
      "Add the reserved pasta water to the skillet and let simmer. Add pasta and all grated cheese. Stir and toss until cheese melts and creates creamy texture. Then the pasta is ready to serve.",
    ],
    image: "/image/background.jpg",
  },
  {
    title: "Pizza",
    category: 'dinner',
    country: 'italian',
    date: "March 18 , 2024",
    author: "Mohammad Sadeghiani",
    rate: 5,
    note: "Here is we are . Today im gonna show you how can i make potato khelal with soas.",
    ingredients: ["1kg potato", "50cc oil", "200g soas"],
    time: "22 minutes",
    step: [
      "Boil water in a pot. Season it with salt and then add pasta to cook.Stir occassionally until the pasta get tender.Before draining pasta reserve 3/4 cup of pasta cooking water.",
      "On a medium large skillet melt butter. Once the butter is melted, keep the temperature on medium heat and add pepper, cook until the pepper is toasted",
      "Add the reserved pasta water to the skillet and let simmer. Add pasta and all grated cheese. Stir and toss until cheese melts and creates creamy texture. Then the pasta is ready to serve.",
    ],
    image: "/image/pizza.jpg",
  },
  {
    title: "Burger",
    category: 'dinner',
    country: 'italian',
    date: "March 18 , 2024",
    author: "Mohammad Sadeghiani",
    rate: 2,
    note: "Here is we are . Today im gonna show you how can i make potato khelal with soas.",
    ingredients: ["1kg potato", "50cc oil", "200g soas"],
    time: "13 minutes",
    step: [
      "Boil water in a pot. Season it with salt and then add pasta to cook.Stir occassionally until the pasta get tender.Before draining pasta reserve 3/4 cup of pasta cooking water.",
      "On a medium large skillet melt butter. Once the butter is melted, keep the temperature on medium heat and add pepper, cook until the pepper is toasted",
      "Add the reserved pasta water to the skillet and let simmer. Add pasta and all grated cheese. Stir and toss until cheese melts and creates creamy texture. Then the pasta is ready to serve.",
    ],
    image: "/image/burger.jpg",
  },
  {
    title: "Scrambled Eggs",
    image: '/image/scrambled_egg.jpg',
    date : '19 Feb 2024',
    rate : 1,
    author: 'Mohammad Sadeghiani',
    time: '6 minutes',
    category: 'breakfast',
    country: 'english',
    ingredients: [
      "eggs: 2",
      "milk: 2 tablespoons",
      "butter: 1 tablespoon",
      "salt: to taste",
      "pepper: to taste",
      "cheese: shredded, any kind",
    ],
    step: [
      "Crack the eggs into a bowl and whisk them together with the milk.",
      "Heat the butter in a pan over medium heat.",
      "Pour the egg mixture into the pan and let it cook for a minute, then gently stir the eggs with a spatula.",
      "Continue to stir the eggs until they are cooked through to your desired consistency.",
      "Season with salt and pepper to taste.",
      "**Optional:** Add cheese and/or chopped vegetables during step 3 and cook them with the eggs.",
    ],
    note: "This is a basic recipe for scrambled eggs. You can adjust the amount of milk, butter, salt, and pepper to your liking. You can also add other ingredients, such as chopped ham, sausage, or herbs.",
  },
];
export default dinner;
